# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Vinti's Blog
tagline:          Life is beautiful
url:              http://vintimaheshwari.com
paginate:         1
baseurl:          /
author:
  name:           Vinti Maheshwari
  url:
  email:          vinti.uiet@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/vibhuti
